package com.crmindz.bcjmay2017.dao;

import java.util.List;

import com.crmindz.bcjmay2017.pojo.Ticket;

/**
 * @author Siva Reddy. 
 * 		   Acts as an Interface which contains only
 *         Abstract methods Implemented by various classes.
 */
public interface TicketDAO {

	/**
	 * Gets category's from reference table in database.
	 * 
	 * @return Returns a list of map's.
	 */
	public List<String> getTicketCategoryInfo();

	
	/**
	 * Gets sub categories of a category.
	 * 
	 * @param categoryValue
	 *            Has category value.
	 * @return Return's a list of map's.
	 */
	public List<String> getTicketSubCategoryInfo(String ticketCategoryName);

	
	/**
	 * Saves the ticket generated by the user.
	 * 
	 * @param ticket
	 *            Contains ticket details to be saved.
	 * @return Returns boolean based on the insert query.
	 */
	public boolean createTicket(Ticket ticket, int userId);

	
	/**
	 * Gets the tickets generated by this user.
	 * 
	 * @param userId
	 *            User Id.
	 * @return Returns a list of map's that has generated tickets.
	 */
	public List<Ticket> getTicketsListByUserId(int user_Id);


}
